image: derh4nnes/pipeline-behat:latest
clone:
  depth: full
options:
  size: 2x
pipelines:
  default:
    - step:
        name: Build and test
        caches:
          - composer
        script:
          - apt-get update
          - apt-get install -y screen
          - curl -sL https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh -o install_nvm.sh
          - bash install_nvm.sh
          - source ~/.profile
          - nvm install 9.11.1
          - export PATH="$HOME/.composer/vendor/bin:$PATH"
          - cd ..
          - mkdir permissions_by_term/
          - mv build/* permissions_by_term/
          - mv permissions_by_term/ build/
          - cd build
          - composer create-project drupal-composer/drupal-project:8.x-dev drupal --stability dev --no-interaction
          - (cd drupal && composer require twig/twig:~1.37.0 behat/behat:^3.0 behat/mink-extension:^2.2 drupal/drupal-extension:^3.2 --dev)
          - mv permissions_by_term drupal/web/modules/
          - (cd drupal/web/modules/permissions_by_term/tests/ && ../../../../vendor/bin/phpunit --testdox)
          - (cd drupal/web/modules/permissions_by_term/js/ && npm install && npm run bat)
          - (cd drupal/web && ../vendor/drush/drush/drush si standard --db-url=mysql://root:testing@127.0.01/testing -y && ../vendor/drush/drush/drush en permissions_by_term -y)
          - (cd drupal && cp web/modules/permissions_by_term/tests/src/Behat/composer-require-namespace.php . && php composer-require-namespace.php && composer dump-autoload)
          - (cd drupal/web && screen -dmS php-server php -S localhost:80 .ht.router.php)
          - (cd drupal/web && cp modules/permissions_by_term/tests/src/Behat/behat.yml.dist behat.yml && ../vendor/bin/behat)
        services:
          - testing
          - mysql
    - step:
        name: Deploy
        script:
          - apt-get update && apt-get install -y unzip git
          - git remote add d.o jepSter@git.drupal.org:project/permissions_by_term.git
          - git config --global push.default simple
          - git config --global user.name "Peter Majmesku"
          - git push -u d.o
definitions:
  services:
    testing:
      image: darksolar/selenium-chrome-headless
    mysql:
      image: mechtecs/docker_big_mysql
      environment:
        MYSQL_ROOT_PASSWORD: testing
        MYSQL_DATABASE: testing
