permissions_by_term.settings:
  type: config_object
  label: 'Permissions by Term settings'
  mapping:
    permission_mode:
      type: boolean
      label: 'Permission mode'
    require_all_terms_granted:
      type: boolean
      label: 'Require all terms granted'
    disable_node_access_records:
      type: boolean
      label: 'Disable node access records'
    target_bundles:
      type: sequence
      label: 'Limit by taxonomy vocabularies'
      sequence:
        type: string
