# This schema tells the config system how to read our config YML files.
# See for example the file config/config_entity_example.robot.marvin.yml, which
# contains our default config entity.

# Documentation for schema files like this one is located here:
# https://drupal.org/node/1905070

permissions_by_term.settings.*:
  type: mapping
  label: 'Settings'
  mapping:
    id:
      type: string
      label: 'Id'
    value:
      type: boolean
      label: 'Value'
    langcode:
      type: string
      label: 'Default language'